// Mapping of item names to image paths
// Images are in public/images/items/{category}/{type}.webp
// Dodaj końcówkę np: '/images/items/1/' -> '/images/items/1/0.webp'

const ITEM_IMAGES: Record<string, string | null> = {
  // ==================== Category 0 - Swords ====================
  'Short Sword': '/images/items/0/1.webp',
  'Kris': '/images/items/0/0.webp',
  'Rapier': '/images/items/0/2.webp',
  'Sword of Assassin': '/images/items/0/4.webp',
  'Katana': '/images/items/0/3.webp',
  'Gladius': '/images/items/0/6.webp',
  'Falchion': '/images/items/0/7.webp',
  'Serpent Sword': '/images/items/0/5.webp',
  'Sword of Salamander': '/images/items/0/8.webp',
  'Light Saber': '/images/items/0/10.webp',
  'Legendary Sword': '/images/items/0/9.webp',
  'Double Blade': '/images/items/0/13.webp',
  'Giant Sword': '/images/items/0/15.webp',
  'Heliacal Sword': '/images/items/0/12.webp',
  'Lighting Sword': '/images/items/0/14.webp',
  'Sword of Destruction': '/images/items/0/16.webp',
  'Divine Sword of Archangel': '/images/items/0/19.webp',
  'Rune Blade': '/images/items/0/31.webp',
  'Dark Breaker': '/images/items/0/17.webp',
  'Thunder Blade': '/images/items/0/18.webp',
  'Daybreak': '/images/items/0/24.webp',
  'Sword Dancer': '/images/items/0/25.webp',
  'Knight Blade': '/images/items/0/20.webp',
  'Dark Reign Blade': '/images/items/0/21.webp',
  'Bone Blade': '/images/items/0/22.webp',
  'Explosion Blade': '/images/items/0/23.webp',
  'Flameberge': '/images/items/0/26.webp',
  'Sword Breaker': '/images/items/0/27.webp',
  'Rune Bastard Sword': '/images/items/0/28.webp',

  // ==================== Category 1 - Axes ====================
  'Small Axe': '/images/items/1/0.webp',
  'Hand Axe': '/images/items/1/1.webp',
  'Double Axe': '/images/items/1/2.webp',
  'Tomahawk': '/images/items/1/3.webp',
  'Elven Axe': '/images/items/1/4.webp',
  'Battle Axe': '/images/items/1/5.webp',
  'Nikea Axe': '/images/items/1/6.webp',
  'Larkan Axe': '/images/items/1/7.webp',
  'Crescent Axe': '/images/items/1/8.webp',

  // ==================== Category 2 - Maces ====================
  'Mace': '/images/items/2/0.webp',
  'Morning Star': '/images/items/2/1.webp',
  'Flail': '/images/items/2/2.webp',
  'Great Hammer': '/images/items/2/3.webp',
  'Battle Scepter': '/images/items/2/8.webp',
  'Crystal Morning Star': '/images/items/2/4.webp',
  'Crystal Sword': '/images/items/2/5.webp',
  'Master Scepter': '/images/items/2/9.webp',
  'Great Scepter': '/images/items/2/10.webp',
  'Elemental Mace': '/images/items/2/7.webp',
  'Lord Scepter': '/images/items/2/11.webp',
  'Shining Scepter': '/images/items/2/15.webp',
  'Great Lord Scepter': '/images/items/2/12.webp',
  'Soleil Scepter': '/images/items/2/14.webp',
  'Frost Mace': '/images/items/2/16',
  'Divine Scepter of Archangel': '/images/items/2/13.webp',

  // ==================== Category 3 - Spears ====================
  'Double Poleaxe': '/images/items/3/3.webp',
  'Dragon Lance': '/images/items/3/2.webp',
  'Halberd': '/images/items/3/6.webp',
  'Spear': '/images/items/3/1.webp',
  'Giant Trident': '/images/items/3/5.webp',
  'Berdysh': '/images/items/3/7.webp',
  'Light Spear': '/images/items/3/0.webp',
  'Serpent Spear': '/images/items/3/4.webp',
  'Great Scythe': '/images/items/3/8.webp',
  'Bill of Balrog': '/images/items/3/9.webp',
  'Dragon Spear': '/images/items/3/10.webp',

  // ==================== Category 4 - Bows ====================
  'Short Bow': '/images/items/4/1.webp',
  'Crossbow': '/images/items/4/8.webp',
  'Bow': '/images/items/4/0.webp',
  'Golden Crossbow': '/images/items/4/9.webp',
  'Elven Bow': '/images/items/4/2.webp',
  'Arquebus': '/images/items/4/10.webp',
  'Battle Bow': '/images/items/4/3.webp',
  'Light Crossbow': '/images/items/4/11.webp',
  'Tiger Bow': '/images/items/4/4.webp',
  'Serpent Crossbow': '/images/items/4/12.webp',
  'Silver Bow': '/images/items/4/5.webp',
  'Bluewing Crossbow': '/images/items/4/13.webp',
  'Aquagold Crossbow': '/images/items/4/14.webp',
  'Saint Crossbow': '/images/items/4/16.webp',
  'Celestial Bow': '/images/items/4/17.webp',
  'Divine Crossbow of Archangel': '/images/items/4/18.webp',
  'Great Reign Crossbow': '/images/items/4/19.webp',
  'Albatross Bow': '/images/items/4/22.webp',
  'Arrow Viper Bow': '/images/items/4/20.webp',
  'Sylph Wind Bow': '/images/items/4/21.webp',

  // ==================== Category 6 - Shields ====================
  'Small Shield': '/images/items/6/0.webp',
  'Buckler': '/images/items/6/4.webp',
  'Horn Shield': '/images/items/6/1.webp',
  'Kite Shield': '/images/items/6/2.webp',
  'Skull Shield': '/images/items/6/6.webp',
  'Large Round Shield': '/images/items/6/10.webp',
  'Elven Shield': '/images/items/6/3.webp',
  'Plate Shield': '/images/items/6/9.webp',
  'Spiked Shield': '/images/items/6/7.webp',
  'Dragon Slayer Shield': '/images/items/6/5.webp',
  'Tower Shield': '/images/items/6/8.webp',
  'Serpent Shield': '/images/items/6/11.webp',
  'Legendary Shield': '/images/items/6/14.webp',
  'Bronze Shield': '/images/items/6/12.webp',
  'Dragon Shield': '/images/items/6/13.webp',
  'Elemental Shield': '/images/items/6/16.webp',
  'Cross Shield': '/images/items/6/21.webp',
  'Grand Soul Shield': '/images/items/6/15.webp',
  'Frost Barrier': '/images/items/6/19.webp',
  'Salamander Shield': '/images/items/6/18.webp',
  'Crimson Glory': '/images/items/6/17.webp',
  'Guardian Shield': '/images/items/6/20.webp',

  // ==================== Category 7 - Helms ====================
  'Dragon Helm': '/images/items/7/1.webp',
  'Legendary Helm': '/images/items/7/3.webp',
  'Leather Helm': '/images/items/7/5.webp',
  'Vine Helm': '/images/items/7/10.webp',
  'Silk Helm': '/images/items/7/11.webp',
  'Bone Helm': '/images/items/7/4.webp',
  'Scale Helm': '/images/items/7/6.webp',
  'Wind Helm': '/images/items/7/12.webp',
  'Violent Wind Helm': '/images/items/7/39.webp',
  'Sphinx Mask': '/images/items/7/7.webp',
  'Brass Helm': '/images/items/7/8.webp',
  'Spirit Helm': '/images/items/7/13.webp',
  'Plate Helm': '/images/items/7/9.webp',
  'Light Plate Mask': '/images/items/7/25.webp',
  'Red Wing Helm': '/images/items/7/40.webp',
  'Guardian Helm': '/images/items/7/14.webp',
  'Adamantine Mask': '/images/items/7/26.webp',
  'Ashcrow Helm': '/images/items/7/34.webp',
  'Eclipse Helm': '/images/items/7/35.webp',
  'Iris Helm': '/images/items/7/36.webp',
  'Ancient Helm': '/images/items/7/41.webp',
  'Grand Soul Helm': '/images/items/7/18.webp',
  'Demonic Helm': '/images/items/7/42.webp',
  'Black Dragon Helm': '/images/items/7/16.webp',
  'Divine Helm': '/images/items/7/19.webp',
  'Dark Steel Mask': '/images/items/7/27.webp',
  'Dark Phoenix Helm': '/images/items/7/17.webp',
  'Red Spirit Helm': '/images/items/7/24.webp',
  'Glorious Mask': '/images/items/7/33.webp',
  'Great Dragon Helm': '/images/items/7/21.webp',
  'Dark Master Mask': '/images/items/7/27.webp',
  'Dark Soul Helm': '/images/items/7/22.webp',
  'Venom Mist Helm': '/images/items/7/30.webp',
  'Sylphid Ray Helm': '/images/items/7/31.webp',
  'Dragon Knight Helm': '/images/items/7/29.webp',
  'Sunlight Mask': '/images/items/7/33.webp',

  // ==================== Category 8 - Armor ====================
  'Dragon Armor': '/images/items/8/1.webp',
  'Legendary Armor': '/images/items/8/3.webp',
  'Leather Armor': '/images/items/8/5.webp',
  'Vine Armor': '/images/items/8/10.webp',
  'Silk Armor': '/images/items/8/11.webp',
  'Bone Armor': '/images/items/8/4.webp',
  'Scale Armor': '/images/items/8/6.webp',
  'Wind Armor': '/images/items/8/12.webp',
  'Violent Wind Armor': '/images/items/8/39.webp',
  'Sphinx Armor': '/images/items/8/7.webp',
  'Brass Armor': '/images/items/8/8.webp',
  'Spirit Armor': '/images/items/8/13.webp',
  'Plate Armor': '/images/items/8/9.webp',
  'Red Wing Armor': '/images/items/8/40.webp',
  'Guardian Armor': '/images/items/8/14.webp',
  'Light Plate Armor': '/images/items/8/25.webp',
  'Ashcrow Armor': '/images/items/8/34.webp',
  'Eclipse Armor': '/images/items/8/35.webp',
  'Iris Armor': '/images/items/8/36.webp',
  'Ancient Armor': '/images/items/8/41.webp',
  'Adamantine Armor': '/images/items/8/26.webp',
  'Storm Crow Armor': '/images/items/8/15.webp',
  'Black Dragon Armor': '/images/items/8/16.webp',
  'Grand Soul Armor': '/images/items/8/18.webp',
  'Demonic Armor': '/images/items/8/42.webp',
  'Divine Armor': '/images/items/8/19.webp',
  'Dark Steel Armor': '/images/items/8/27.webp',
  'Dark Phoenix Armor': '/images/items/8/17.webp',
  'Valiant Armor': '/images/items/8/37.webp',
  'Glorious Armor': '/images/items/8/33.webp',
  'Thunder Hawk Armor': '/images/items/8/20.webp',
  'Red Spirit Armor': '/images/items/8/24.webp',
  'Dark Master Armor': '/images/items/8/27.webp',
  'Dark Soul Armor': '/images/items/8/22.webp',
  'Great Dragon Armor': '/images/items/8/21.webp',
  'Hurricane Armor': '/images/items/8/23.webp',
  'Dragon Knight Armor': '/images/items/8/29.webp',
  'Venom Mist Armor': '/images/items/8/30.webp',
  'Sylphid Ray Armor': '/images/items/8/31.webp',
  'Volcano Armor': '/images/items/8/32.webp',
  'Sunlight Armor': '/images/items/8/33.webp',

  // ==================== Category 9 - Pants ====================
  'Dragon Pants': '/images/items/9/1.webp',
  'Legendary Pants': '/images/items/9/3.webp',
  'Leather Pants': '/images/items/9/5.webp',
  'Vine Pants': '/images/items/9/10.webp',
  'Silk Pants': '/images/items/9/11.webp',
  'Bone Pants': '/images/items/9/4.webp',
  'Scale Pants': '/images/items/9/6.webp',
  'Wind Pants': '/images/items/9/12.webp',
  'Violent Wind Pants': '/images/items/9/39.webp',
  'Sphinx Pants': '/images/items/9/7.webp',
  'Brass Pants': '/images/items/9/8.webp',
  'Spirit Pants': '/images/items/9/13.webp',
  'Plate Pants': '/images/items/9/9.webp',
  'Light Plate Pants': '/images/items/9/25.webp',
  'Red Wing Pants': '/images/items/9/40.webp',
  'Guardian Pants': '/images/items/9/14.webp',
  'Ashcrow Pants': '/images/items/9/34.webp',
  'Eclipse Pants': '/images/items/9/35.webp',
  'Iris Pants': '/images/items/9/36.webp',
  'Adamantine Pants': '/images/items/9/26.webp',
  'Ancient Pants': '/images/items/9/41.webp',
  'Storm Crow Pants': '/images/items/9/15.webp',
  'Black Dragon Pants': '/images/items/9/16.webp',
  'Grand Soul Pants': '/images/items/9/18.webp',
  'Demonic Pants': '/images/items/9/42.webp',
  'Divine Pants': '/images/items/9/19.webp',
  'Dark Steel Pants': '/images/items/9/27.webp',
  'Dark Phoenix Pants': '/images/items/9/17.webp',
  'Thunder Hawk Pants': '/images/items/9/20.webp',
  'Red Spirit Pants': '/images/items/9/24.webp',
  'Valiant Pants': '/images/items/9/37.webp',
  'Glorious Pants': '/images/items/9/33.webp',
  'Dark Master Pants': '/images/items/9/27.webp',
  'Great Dragon Pants': '/images/items/9/21.webp',
  'Dark Soul Pants': '/images/items/9/22.webp',
  'Hurricane Pants': '/images/items/9/23.webp',
  'Dragon Knight Pants': '/images/items/9/29.webp',
  'Venom Mist Pants': '/images/items/9/30.webp',
  'Sylphid Ray Pants': '/images/items/9/31.webp',
  'Volcano Pants': '/images/items/9/32.webp',
  'Sunlight Pants': '/images/items/9/33.webp',

  // ==================== Category 10 - Gloves ====================
  'Dragon Gloves': '/images/items/10/1.webp',
  'Legendary Gloves': '/images/items/10/3.webp',
  'Leather Gloves': '/images/items/10/5.webp',
  'Vine Gloves': '/images/items/10/10.webp',
  'Silk Gloves': '/images/items/10/11.webp',
  'Bone Gloves': '/images/items/10/4.webp',
  'Scale Gloves': '/images/items/10/6.webp',
  'Violent Wind Gloves': '/images/items/10/39.webp',
  'Wind Gloves': '/images/items/10/12.webp',
  'Sphinx Gloves': '/images/items/10/7.webp',
  'Brass Gloves': '/images/items/10/8.webp',
  'Spirit Gloves': '/images/items/10/13.webp',
  'Plate Gloves': '/images/items/10/9.webp',
  'Light Plate Gloves': '/images/items/10/25.webp',
  'Red Wing Gloves': '/images/items/10/40.webp',
  'Guardian Gloves': '/images/items/10/14.webp',
  'Adamantine Gloves': '/images/items/10/26.webp',
  'Ashcrow Gloves': '/images/items/10/34.webp',
  'Eclipse Gloves': '/images/items/10/35.webp',
  'Iris Gloves': '/images/items/10/36.webp',
  'Ancient Gloves': '/images/items/10/41.webp',
  'Storm Crow Gloves': '/images/items/10/15.webp',
  'Grand Soul Gloves': '/images/items/10/18.webp',
  'Demonic Gloves': '/images/items/10/42.webp',
  'Divine Gloves': '/images/items/10/19.webp',
  'Dark Steel Gloves': '/images/items/10/27.webp',
  'Black Dragon Gloves': '/images/items/10/16.webp',
  'Red Spirit Gloves': '/images/items/10/24.webp',
  'Dark Phoenix Gloves': '/images/items/10/17.webp',
  'Dark Soul Gloves': '/images/items/10/22.webp',
  'Thunder Hawk Gloves': '/images/items/10/20.webp',
  'Dark Master Gloves': '/images/items/10/27.webp',
  'Valiant Gloves': '/images/items/10/37.webp',
  'Glorious Gloves': '/images/items/10/33.webp',
  'Great Dragon Gloves': '/images/items/10/21.webp',
  'Hurricane Gloves': '/images/items/10/23.webp',
  'Sunlight Gloves': '/images/items/10/33.webp',
  'Venom Mist Gloves': '/images/items/10/30.webp',
  'Sylphid Ray Gloves': '/images/items/10/31.webp',
  'Dragon Knight Gloves': '/images/items/10/29.webp',
  'Volcano Gloves': '/images/items/10/32.webp',

  // ==================== Category 11 - Boots ====================
  'Dragon Boots': '/images/items/11/1.webp',
  'Legendary Boots': '/images/items/11/3.webp',
  'Leather Boots': '/images/items/11/5.webp',
  'Vine Boots': '/images/items/11/10.webp',
  'Silk Boots': '/images/items/11/11.webp',
  'Bone Boots': '/images/items/11/4.webp',
  'Scale Boots': '/images/items/11/6.webp',
  'Violent Wind Boots': '/images/items/11/39.webp',
  'Wind Boots': '/images/items/11/12.webp',
  'Sphinx Boots': '/images/items/11/7.webp',
  'Brass Boots': '/images/items/11/8.webp',
  'Spirit Boots': '/images/items/11/13.webp',
  'Plate Boots': '/images/items/11/9.webp',
  'Light Plate Boots': '/images/items/11/25.webp',
  'Red Wing Boots': '/images/items/11/40.webp',
  'Guardian Boots': '/images/items/11/14.webp',
  'Adamantine Boots': '/images/items/11/26.webp',
  'Ancient Boots': '/images/items/11/41.webp',
  'Ashcrow Boots': '/images/items/11/34.webp',
  'Eclipse Boots': '/images/items/11/35.webp',
  'Iris Boots': '/images/items/11/36.webp',
  'Storm Crow Boots': '/images/items/11/15.webp',
  'Grand Soul Boots': '/images/items/11/18.webp',
  'Demonic Boots': '/images/items/11/42.webp',
  'Black Dragon Boots': '/images/items/11/16.webp',
  'Divine Boots': '/images/items/11/19.webp',
  'Dark Steel Boots': '/images/items/11/27.webp',
  'Red Spirit Boots': '/images/items/11/24.webp',
  'Thunder Hawk Boots': '/images/items/11/20.webp',
  'Dark Phoenix Boots': '/images/items/11/17.webp',
  'Dark Master Boots': '/images/items/11/27.webp',
  'Dark Soul Boots': '/images/items/11/22.webp',
  'Great Dragon Boots': '/images/items/11/21.webp',
  'Valiant Boots': '/images/items/11/37.webp',
  'Glorious Boots': '/images/items/11/33.webp',
  'Hurricane Boots': '/images/items/11/23.webp',
  'Dragon Knight Boots': '/images/items/11/29.webp',
  'Venom Mist Boots': '/images/items/11/30.webp',
  'Sylphid Ray Boots': '/images/items/11/31.webp',
  'Sunlight Boots': '/images/items/11/33.webp',
  'Volcano Boots': '/images/items/11/32.webp',

  // ==================== Category 12 - Rings ====================
  'Ring of Ice': '/images/items/12/8.webp',
  'Ring of Poison': '/images/items/12/9.webp',
  'Ring of Fire': '/images/items/12/21.webp',
  'Ring of Earth': '/images/items/12/22.webp',
  'Ring of Wind': '/images/items/12/23.webp',
  'Ring of Magic': '/images/items/12/24.webp',

  // ==================== Category 13 - Pendants ====================
  'Pendant of Lightning': '/images/items/13/12.webp',
  'Pendant of Fire': '/images/items/13/13.webp',
  'Pendant of Ice': '/images/items/13/25.webp',
  'Pendant of Wind': '/images/items/13/26.webp',
  'Pendant of Water': '/images/items/13/27.webp',
  'Pendant of Ability': '/images/items/13/28.webp',
};

export function getItemImagePath(itemName: string): string | null {
  const path = ITEM_IMAGES[itemName];
  // Zwraca null jeśli ścieżka kończy się na '/' (brak końcówki = brak obrazka)
  if (!path || path.endsWith('/')) return null;
  return path;
}

export function hasItemImage(itemName: string): boolean {
  const path = ITEM_IMAGES[itemName];
  return path != null && !path.endsWith('/');
}

// Rozmiary itemów (domyślnie 76px, tutaj tylko wyjątki)
const ITEM_SIZES: Record<string, number> = {
  // Armor - mniejsze
  'Plate Armor': 50,

  // Ringi - mniejsze
  'Ring of Ice': 52,
  'Ring of Poison': 52,
  'Ring of Fire': 52,
  'Ring of Earth': 52,
  'Ring of Wind': 52,
  'Ring of Magic': 52,

  // Pendanty - mniejsze
  'Pendant of Lightning': 44,
  'Pendant of Fire': 44,
  'Pendant of Ice': 44,
  'Pendant of Wind': 44,
  'Pendant of Water': 44,
  'Pendant of Ability': 44,
};

const DEFAULT_ITEM_SIZE = 76;

export function getItemImageSize(itemName: string): number {
  return ITEM_SIZES[itemName] ?? DEFAULT_ITEM_SIZE;
}
