import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

const items = [
  // Category 0 - Swords
  { type: 0, slot: 0, name: 'Short Sword', level: 3, damageMin: 3, damageMax: 7, attackSpeed: 20, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 1, slot: 0, name: 'Kris', level: 6, damageMin: 6, damageMax: 11, attackSpeed: 50, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 2, slot: 0, name: 'Rapier', level: 9, damageMin: 9, damageMax: 15, attackSpeed: 40, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 3, slot: 0, name: 'Sword of Assassin', level: 12, damageMin: 12, damageMax: 18, attackSpeed: 30, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 4, slot: 0, name: 'Katana', level: 16, damageMin: 16, damageMax: 26, attackSpeed: 35, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 5, slot: 0, name: 'Gladius', level: 20, damageMin: 20, damageMax: 30, attackSpeed: 20, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 6, slot: 0, name: 'Falchion', level: 24, damageMin: 24, damageMax: 34, attackSpeed: 25, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 7, slot: 0, name: 'Serpent Sword', level: 30, damageMin: 30, damageMax: 40, attackSpeed: 20, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 8, slot: 0, name: 'Sword of Salamander', level: 32, damageMin: 32, damageMax: 46, attackSpeed: 30, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 9, slot: 0, name: 'Light Saber', level: 40, damageMin: 47, damageMax: 61, attackSpeed: 25, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 10, slot: 0, name: 'Legendary Sword', level: 44, damageMin: 56, damageMax: 72, attackSpeed: 20, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 11, slot: 0, name: 'Double Blade', level: 48, damageMin: 48, damageMax: 56, attackSpeed: 30, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 12, slot: 0, name: 'Giant Sword', level: 52, damageMin: 60, damageMax: 85, attackSpeed: 20, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 13, slot: 0, name: 'Heliacal Sword', level: 56, damageMin: 73, damageMax: 98, attackSpeed: 25, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 14, slot: 0, name: 'Lighting Sword', level: 59, damageMin: 59, damageMax: 67, attackSpeed: 30, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 15, slot: 0, name: 'Sword of Destruction', level: 82, damageMin: 82, damageMax: 90, attackSpeed: 35, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 16, slot: 0, name: 'Divine Sword of Archangel', level: 86, damageMin: 120, damageMax: 130, attackSpeed: 35, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 17, slot: 0, name: 'Rune Blade', level: 100, damageMin: 104, damageMax: 130, attackSpeed: 35, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 18, slot: 0, name: 'Dark Breaker', level: 104, damageMin: 128, damageMax: 153, attackSpeed: 40, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 19, slot: 0, name: 'Thunder Blade', level: 105, damageMin: 140, damageMax: 168, attackSpeed: 40, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 20, slot: 0, name: 'Daybreak', level: 115, damageMin: 182, damageMax: 218, attackSpeed: 40, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 21, slot: 0, name: 'Sword Dancer', level: 115, damageMin: 109, damageMax: 136, attackSpeed: 40, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 22, slot: 0, name: 'Knight Blade', level: 140, damageMin: 107, damageMax: 115, attackSpeed: 35, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 23, slot: 0, name: 'Dark Reign Blade', level: 140, damageMin: 115, damageMax: 142, attackSpeed: 40, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 24, slot: 0, name: 'Bone Blade', level: 147, damageMin: 122, damageMax: 135, attackSpeed: 40, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 25, slot: 0, name: 'Explosion Blade', level: 147, damageMin: 127, damageMax: 155, attackSpeed: 45, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 26, slot: 0, name: 'Flameberge', level: 147, damageMin: 115, damageMax: 126, attackSpeed: 40, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 27, slot: 0, name: 'Sword Breaker', level: 147, damageMin: 91, damageMax: 99, attackSpeed: 35, defenseValue: 0, category: 0, emoji: '⚔️' },
  { type: 28, slot: 0, name: 'Rune Bastard Sword', level: 147, damageMin: 98, damageMax: 122, attackSpeed: 45, defenseValue: 0, category: 0, emoji: '⚔️' },

  // Category 1 - Axes
  { type: 0, slot: 0, name: 'Small Axe', level: 1, damageMin: 1, damageMax: 6, attackSpeed: 20, defenseValue: 0, category: 1, emoji: '🪓' },
  { type: 1, slot: 0, name: 'Hand Axe', level: 4, damageMin: 4, damageMax: 9, attackSpeed: 30, defenseValue: 0, category: 1, emoji: '🪓' },
  { type: 2, slot: 0, name: 'Double Axe', level: 14, damageMin: 14, damageMax: 24, attackSpeed: 20, defenseValue: 0, category: 1, emoji: '🪓' },
  { type: 3, slot: 0, name: 'Tomahawk', level: 18, damageMin: 18, damageMax: 28, attackSpeed: 30, defenseValue: 0, category: 1, emoji: '🪓' },
  { type: 4, slot: 0, name: 'Elven Axe', level: 26, damageMin: 26, damageMax: 38, attackSpeed: 40, defenseValue: 0, category: 1, emoji: '🪓' },
  { type: 5, slot: 0, name: 'Battle Axe', level: 30, damageMin: 36, damageMax: 44, attackSpeed: 20, defenseValue: 0, category: 1, emoji: '🪓' },
  { type: 6, slot: 0, name: 'Nikea Axe', level: 34, damageMin: 38, damageMax: 50, attackSpeed: 30, defenseValue: 0, category: 1, emoji: '🪓' },
  { type: 7, slot: 0, name: 'Larkan Axe', level: 46, damageMin: 54, damageMax: 67, attackSpeed: 25, defenseValue: 0, category: 1, emoji: '🪓' },
  { type: 8, slot: 0, name: 'Crescent Axe', level: 54, damageMin: 69, damageMax: 89, attackSpeed: 30, defenseValue: 0, category: 1, emoji: '🪓' },

  // Category 2 - Maces
  { type: 0, slot: 0, name: 'Mace', level: 7, damageMin: 7, damageMax: 13, attackSpeed: 15, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 1, slot: 0, name: 'Morning Star', level: 13, damageMin: 13, damageMax: 22, attackSpeed: 15, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 2, slot: 0, name: 'Flail', level: 22, damageMin: 22, damageMax: 32, attackSpeed: 15, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 3, slot: 0, name: 'Great Hammer', level: 38, damageMin: 45, damageMax: 56, attackSpeed: 15, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 4, slot: 0, name: 'Battle Scepter', level: 54, damageMin: 41, damageMax: 52, attackSpeed: 45, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 5, slot: 0, name: 'Crystal Morning Star', level: 66, damageMin: 78, damageMax: 107, attackSpeed: 30, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 6, slot: 0, name: 'Crystal Sword', level: 72, damageMin: 89, damageMax: 120, attackSpeed: 40, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 7, slot: 0, name: 'Master Scepter', level: 72, damageMin: 57, damageMax: 68, attackSpeed: 45, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 8, slot: 0, name: 'Great Scepter', level: 82, damageMin: 74, damageMax: 85, attackSpeed: 45, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 9, slot: 0, name: 'Elemental Mace', level: 90, damageMin: 62, damageMax: 80, attackSpeed: 50, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 10, slot: 0, name: 'Lord Scepter', level: 98, damageMin: 91, damageMax: 102, attackSpeed: 40, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 11, slot: 0, name: 'Shining Scepter', level: 110, damageMin: 99, damageMax: 111, attackSpeed: 40, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 12, slot: 0, name: 'Great Lord Scepter', level: 140, damageMin: 108, damageMax: 120, attackSpeed: 40, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 13, slot: 0, name: 'Soleil Scepter', level: 146, damageMin: 130, damageMax: 153, attackSpeed: 40, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 14, slot: 0, name: 'Frost Mace', level: 147, damageMin: 106, damageMax: 146, attackSpeed: 50, defenseValue: 0, category: 2, emoji: '🔨' },
  { type: 15, slot: 0, name: 'Divine Scepter of Archangel', level: 150, damageMin: 120, damageMax: 143, attackSpeed: 40, defenseValue: 0, category: 2, emoji: '🔨' },

  // Category 3 - Spears
  { type: 0, slot: 0, name: 'Double Poleaxe', level: 13, damageMin: 19, damageMax: 31, attackSpeed: 30, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 1, slot: 0, name: 'Dragon Lance', level: 15, damageMin: 21, damageMax: 33, attackSpeed: 30, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 2, slot: 0, name: 'Halberd', level: 19, damageMin: 25, damageMax: 35, attackSpeed: 30, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 3, slot: 0, name: 'Spear', level: 23, damageMin: 30, damageMax: 41, attackSpeed: 30, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 4, slot: 0, name: 'Giant Trident', level: 29, damageMin: 35, damageMax: 43, attackSpeed: 25, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 5, slot: 0, name: 'Berdysh', level: 37, damageMin: 42, damageMax: 54, attackSpeed: 30, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 6, slot: 0, name: 'Light Spear', level: 42, damageMin: 50, damageMax: 63, attackSpeed: 25, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 7, slot: 0, name: 'Serpent Spear', level: 46, damageMin: 58, damageMax: 80, attackSpeed: 20, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 8, slot: 0, name: 'Great Scythe', level: 54, damageMin: 71, damageMax: 92, attackSpeed: 25, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 9, slot: 0, name: 'Bill of Balrog', level: 63, damageMin: 76, damageMax: 102, attackSpeed: 25, defenseValue: 0, category: 3, emoji: '🔱' },
  { type: 10, slot: 0, name: 'Dragon Spear', level: 92, damageMin: 112, damageMax: 140, attackSpeed: 35, defenseValue: 0, category: 3, emoji: '🔱' },

  // Category 4 - Bows and Crossbows
  { type: 0, slot: 0, name: 'Short Bow', level: 2, damageMin: 3, damageMax: 5, attackSpeed: 30, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 1, slot: 0, name: 'Crossbow', level: 4, damageMin: 5, damageMax: 8, attackSpeed: 40, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 2, slot: 0, name: 'Bow', level: 8, damageMin: 9, damageMax: 13, attackSpeed: 30, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 3, slot: 0, name: 'Golden Crossbow', level: 12, damageMin: 13, damageMax: 19, attackSpeed: 40, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 4, slot: 0, name: 'Elven Bow', level: 16, damageMin: 17, damageMax: 24, attackSpeed: 30, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 5, slot: 0, name: 'Arquebus', level: 20, damageMin: 22, damageMax: 30, attackSpeed: 40, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 6, slot: 0, name: 'Battle Bow', level: 26, damageMin: 28, damageMax: 37, attackSpeed: 30, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 7, slot: 0, name: 'Light Crossbow', level: 32, damageMin: 35, damageMax: 44, attackSpeed: 40, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 8, slot: 0, name: 'Tiger Bow', level: 40, damageMin: 42, damageMax: 52, attackSpeed: 30, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 9, slot: 0, name: 'Serpent Crossbow', level: 48, damageMin: 50, damageMax: 61, attackSpeed: 40, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 10, slot: 0, name: 'Silver Bow', level: 56, damageMin: 59, damageMax: 71, attackSpeed: 40, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 11, slot: 0, name: 'Bluewing Crossbow', level: 68, damageMin: 68, damageMax: 82, attackSpeed: 40, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 12, slot: 0, name: 'Aquagold Crossbow', level: 72, damageMin: 78, damageMax: 92, attackSpeed: 30, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 13, slot: 0, name: 'Saint Crossbow', level: 84, damageMin: 102, damageMax: 127, attackSpeed: 35, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 14, slot: 0, name: 'Celestial Bow', level: 92, damageMin: 127, damageMax: 155, attackSpeed: 35, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 15, slot: 0, name: 'Divine Crossbow of Archangel', level: 100, damageMin: 144, damageMax: 166, attackSpeed: 35, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 16, slot: 0, name: 'Great Reign Crossbow', level: 100, damageMin: 150, damageMax: 172, attackSpeed: 40, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 17, slot: 0, name: 'Albatross Bow', level: 110, damageMin: 155, damageMax: 177, attackSpeed: 45, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 18, slot: 0, name: 'Arrow Viper Bow', level: 135, damageMin: 166, damageMax: 190, attackSpeed: 45, defenseValue: 0, category: 4, emoji: '🏹' },
  { type: 19, slot: 0, name: 'Sylph Wind Bow', level: 147, damageMin: 177, damageMax: 200, attackSpeed: 45, defenseValue: 0, category: 4, emoji: '🏹' },

  // Category 6 - Shields
  { type: 0, slot: 1, name: 'Small Shield', level: 3, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 1, category: 6, emoji: '🛡️' },
  { type: 1, slot: 1, name: 'Buckler', level: 6, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 2, category: 6, emoji: '🛡️' },
  { type: 2, slot: 1, name: 'Horn Shield', level: 9, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 3, category: 6, emoji: '🛡️' },
  { type: 3, slot: 1, name: 'Kite Shield', level: 12, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 4, category: 6, emoji: '🛡️' },
  { type: 4, slot: 1, name: 'Skull Shield', level: 15, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 5, category: 6, emoji: '🛡️' },
  { type: 5, slot: 1, name: 'Large Round Shield', level: 18, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 6, category: 6, emoji: '🛡️' },
  { type: 6, slot: 1, name: 'Elven Shield', level: 21, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 8, category: 6, emoji: '🛡️' },
  { type: 7, slot: 1, name: 'Plate Shield', level: 25, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 8, category: 6, emoji: '🛡️' },
  { type: 8, slot: 1, name: 'Spiked Shield', level: 30, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 9, category: 6, emoji: '🛡️' },
  { type: 9, slot: 1, name: 'Dragon Slayer Shield', level: 35, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 10, category: 6, emoji: '🛡️' },
  { type: 10, slot: 1, name: 'Tower Shield', level: 40, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 11, category: 6, emoji: '🛡️' },
  { type: 11, slot: 1, name: 'Serpent Shield', level: 45, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 12, category: 6, emoji: '🛡️' },
  { type: 12, slot: 1, name: 'Legendary Shield', level: 48, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 7, category: 6, emoji: '🛡️' },
  { type: 13, slot: 1, name: 'Bronze Shield', level: 54, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 13, category: 6, emoji: '🛡️' },
  { type: 14, slot: 1, name: 'Dragon Shield', level: 60, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 14, category: 6, emoji: '🛡️' },
  { type: 15, slot: 1, name: 'Elemental Shield', level: 66, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 11, category: 6, emoji: '🛡️' },
  { type: 16, slot: 1, name: 'Cross Shield', level: 70, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 16, category: 6, emoji: '🛡️' },
  { type: 17, slot: 1, name: 'Grand Soul Shield', level: 74, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 12, category: 6, emoji: '🛡️' },
  { type: 18, slot: 1, name: 'Frost Barrier', level: 99, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 14, category: 6, emoji: '🛡️' },
  { type: 19, slot: 1, name: 'Salamander Shield', level: 102, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 20, category: 6, emoji: '🛡️' },
  { type: 20, slot: 1, name: 'Crimson Glory', level: 104, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 19, category: 6, emoji: '🛡️' },
  { type: 21, slot: 1, name: 'Guardian Shield', level: 106, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 12, category: 6, emoji: '🛡️' },

  // Category 7 - Helms
  { type: 0, slot: 2, name: 'Leather Helm', level: 6, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 5, category: 7, emoji: '⛑️' },
  { type: 1, slot: 2, name: 'Vine Helm', level: 6, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 4, category: 7, emoji: '⛑️' },
  { type: 2, slot: 2, name: 'Silk Helm', level: 16, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 8, category: 7, emoji: '⛑️' },
  { type: 3, slot: 2, name: 'Bone Helm', level: 18, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 9, category: 7, emoji: '⛑️' },
  { type: 4, slot: 2, name: 'Scale Helm', level: 26, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 12, category: 7, emoji: '⛑️' },
  { type: 5, slot: 2, name: 'Wind Helm', level: 28, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 12, category: 7, emoji: '⛑️' },
  { type: 6, slot: 2, name: 'Violent Wind Helm', level: 28, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 13, category: 7, emoji: '⛑️' },
  { type: 7, slot: 2, name: 'Sphinx Mask', level: 32, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 13, category: 7, emoji: '⛑️' },
  { type: 8, slot: 2, name: 'Brass Helm', level: 36, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 17, category: 7, emoji: '⛑️' },
  { type: 9, slot: 2, name: 'Spirit Helm', level: 40, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 16, category: 7, emoji: '⛑️' },
  { type: 10, slot: 2, name: 'Plate Helm', level: 46, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 20, category: 7, emoji: '⛑️' },
  { type: 11, slot: 2, name: 'Light Plate Mask', level: 46, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 20, category: 7, emoji: '⛑️' },
  { type: 12, slot: 2, name: 'Red Wing Helm', level: 50, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 18, category: 7, emoji: '⛑️' },
  { type: 13, slot: 2, name: 'Guardian Helm', level: 53, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 23, category: 7, emoji: '⛑️' },
  { type: 14, slot: 2, name: 'Adamantine Mask', level: 66, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 24, category: 7, emoji: '⛑️' },
  { type: 15, slot: 2, name: 'Ashcrow Helm', level: 67, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 27, category: 7, emoji: '⛑️' },
  { type: 16, slot: 2, name: 'Eclipse Helm', level: 67, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 22, category: 7, emoji: '⛑️' },
  { type: 17, slot: 2, name: 'Iris Helm', level: 67, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 30, category: 7, emoji: '⛑️' },
  { type: 18, slot: 2, name: 'Ancient Helm', level: 68, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 24, category: 7, emoji: '⛑️' },
  { type: 19, slot: 2, name: 'Grand Soul Helm', level: 81, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 27, category: 7, emoji: '⛑️' },
  { type: 20, slot: 2, name: 'Demonic Helm', level: 81, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 32, category: 7, emoji: '⛑️' },
  { type: 21, slot: 2, name: 'Black Dragon Helm', level: 82, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 30, category: 7, emoji: '⛑️' },
  { type: 22, slot: 2, name: 'Divine Helm', level: 85, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 37, category: 7, emoji: '⛑️' },
  { type: 23, slot: 2, name: 'Dark Steel Mask', level: 86, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 26, category: 7, emoji: '⛑️' },
  { type: 24, slot: 2, name: 'Dark Phoenix Helm', level: 92, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 43, category: 7, emoji: '⛑️' },
  { type: 25, slot: 2, name: 'Red Spirit Helm', level: 93, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 46, category: 7, emoji: '⛑️' },
  { type: 26, slot: 2, name: 'Glorious Mask', level: 97, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 30, category: 7, emoji: '⛑️' },
  { type: 27, slot: 2, name: 'Great Dragon Helm', level: 104, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 53, category: 7, emoji: '⛑️' },
  { type: 28, slot: 2, name: 'Dark Master Mask', level: 106, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 34, category: 7, emoji: '⛑️' },
  { type: 29, slot: 2, name: 'Dark Soul Helm', level: 110, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 36, category: 7, emoji: '⛑️' },
  { type: 30, slot: 2, name: 'Venom Mist Helm', level: 126, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 48, category: 7, emoji: '⛑️' },
  { type: 31, slot: 2, name: 'Sylphid Ray Helm', level: 126, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 57, category: 7, emoji: '⛑️' },
  { type: 32, slot: 2, name: 'Dragon Knight Helm', level: 130, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 66, category: 7, emoji: '⛑️' },
  { type: 33, slot: 2, name: 'Sunlight Mask', level: 130, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 46, category: 7, emoji: '⛑️' },

  // Category 8 - Armor
  { type: 0, slot: 3, name: 'Leather Armor', level: 10, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 10, category: 8, emoji: '🦺' },
  { type: 1, slot: 3, name: 'Vine Armor', level: 10, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 8, category: 8, emoji: '🦺' },
  { type: 2, slot: 3, name: 'Silk Armor', level: 20, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 12, category: 8, emoji: '🦺' },
  { type: 3, slot: 3, name: 'Bone Armor', level: 22, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 13, category: 8, emoji: '🦺' },
  { type: 4, slot: 3, name: 'Scale Armor', level: 28, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 18, category: 8, emoji: '🦺' },
  { type: 5, slot: 3, name: 'Wind Armor', level: 32, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 16, category: 8, emoji: '🦺' },
  { type: 6, slot: 3, name: 'Violent Wind Armor', level: 34, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 22, category: 8, emoji: '🦺' },
  { type: 7, slot: 3, name: 'Sphinx Armor', level: 38, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 17, category: 8, emoji: '🦺' },
  { type: 8, slot: 3, name: 'Brass Armor', level: 38, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 22, category: 8, emoji: '🦺' },
  { type: 9, slot: 3, name: 'Spirit Armor', level: 44, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 21, category: 8, emoji: '🦺' },
  { type: 10, slot: 3, name: 'Plate Armor', level: 48, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 30, category: 8, emoji: '🦺' },
  { type: 11, slot: 3, name: 'Red Wing Armor', level: 56, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 28, category: 8, emoji: '🦺' },
  { type: 12, slot: 3, name: 'Guardian Armor', level: 57, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 29, category: 8, emoji: '🦺' },
  { type: 13, slot: 3, name: 'Light Plate Armor', level: 62, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 25, category: 8, emoji: '🦺' },
  { type: 14, slot: 3, name: 'Ashcrow Armor', level: 75, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 42, category: 8, emoji: '🦺' },
  { type: 15, slot: 3, name: 'Eclipse Armor', level: 75, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 27, category: 8, emoji: '🦺' },
  { type: 16, slot: 3, name: 'Iris Armor', level: 75, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 36, category: 8, emoji: '🦺' },
  { type: 17, slot: 3, name: 'Ancient Armor', level: 75, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 35, category: 8, emoji: '🦺' },
  { type: 18, slot: 3, name: 'Adamantine Armor', level: 78, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 36, category: 8, emoji: '🦺' },
  { type: 19, slot: 3, name: 'Storm Crow Armor', level: 80, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 44, category: 8, emoji: '🦺' },
  { type: 20, slot: 3, name: 'Black Dragon Armor', level: 90, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 48, category: 8, emoji: '🦺' },
  { type: 21, slot: 3, name: 'Grand Soul Armor', level: 91, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 33, category: 8, emoji: '🦺' },
  { type: 22, slot: 3, name: 'Demonic Armor', level: 91, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 45, category: 8, emoji: '🦺' },
  { type: 23, slot: 3, name: 'Divine Armor', level: 92, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 44, category: 8, emoji: '🦺' },
  { type: 24, slot: 3, name: 'Dark Steel Armor', level: 96, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 43, category: 8, emoji: '🦺' },
  { type: 25, slot: 3, name: 'Dark Phoenix Armor', level: 100, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 63, category: 8, emoji: '🦺' },
  { type: 26, slot: 3, name: 'Valiant Armor', level: 105, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 52, category: 8, emoji: '🦺' },
  { type: 27, slot: 3, name: 'Glorious Armor', level: 105, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 47, category: 8, emoji: '🦺' },
  { type: 28, slot: 3, name: 'Thunder Hawk Armor', level: 107, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 60, category: 8, emoji: '🦺' },
  { type: 29, slot: 3, name: 'Red Spirit Armor', level: 109, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 55, category: 8, emoji: '🦺' },
  { type: 30, slot: 3, name: 'Dark Master Armor', level: 117, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 51, category: 8, emoji: '🦺' },
  { type: 31, slot: 3, name: 'Dark Soul Armor', level: 122, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 43, category: 8, emoji: '🦺' },
  { type: 32, slot: 3, name: 'Great Dragon Armor', level: 126, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 75, category: 8, emoji: '🦺' },
  { type: 33, slot: 3, name: 'Hurricane Armor', level: 128, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 73, category: 8, emoji: '🦺' },
  { type: 34, slot: 3, name: 'Dragon Knight Armor', level: 140, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 88, category: 8, emoji: '🦺' },
  { type: 35, slot: 3, name: 'Venom Mist Armor', level: 146, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 57, category: 8, emoji: '🦺' },
  { type: 36, slot: 3, name: 'Sylphid Ray Armor', level: 146, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 68, category: 8, emoji: '🦺' },
  { type: 37, slot: 3, name: 'Volcano Armor', level: 147, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 86, category: 8, emoji: '🦺' },
  { type: 38, slot: 3, name: 'Sunlight Armor', level: 147, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 64, category: 8, emoji: '🦺' },

  // Category 9 - Pants
  { type: 0, slot: 4, name: 'Leather Pants', level: 8, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 7, category: 9, emoji: '👖' },
  { type: 1, slot: 4, name: 'Vine Pants', level: 8, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 6, category: 9, emoji: '👖' },
  { type: 2, slot: 4, name: 'Silk Pants', level: 18, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 10, category: 9, emoji: '👖' },
  { type: 3, slot: 4, name: 'Bone Pants', level: 20, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 10, category: 9, emoji: '👖' },
  { type: 4, slot: 4, name: 'Scale Pants', level: 25, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 14, category: 9, emoji: '👖' },
  { type: 5, slot: 4, name: 'Wind Pants', level: 30, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 14, category: 9, emoji: '👖' },
  { type: 6, slot: 4, name: 'Violent Wind Pants', level: 30, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 16, category: 9, emoji: '👖' },
  { type: 7, slot: 4, name: 'Sphinx Pants', level: 34, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 15, category: 9, emoji: '👖' },
  { type: 8, slot: 4, name: 'Brass Pants', level: 35, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 18, category: 9, emoji: '👖' },
  { type: 9, slot: 4, name: 'Spirit Pants', level: 42, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 18, category: 9, emoji: '👖' },
  { type: 10, slot: 4, name: 'Plate Pants', level: 45, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 22, category: 9, emoji: '👖' },
  { type: 11, slot: 4, name: 'Light Plate Pants', level: 50, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 21, category: 9, emoji: '👖' },
  { type: 12, slot: 4, name: 'Red Wing Pants', level: 53, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 22, category: 9, emoji: '👖' },
  { type: 13, slot: 4, name: 'Guardian Pants', level: 54, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 25, category: 9, emoji: '👖' },
  { type: 14, slot: 4, name: 'Ashcrow Pants', level: 69, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 33, category: 9, emoji: '👖' },
  { type: 15, slot: 4, name: 'Eclipse Pants', level: 69, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 25, category: 9, emoji: '👖' },
  { type: 16, slot: 4, name: 'Iris Pants', level: 69, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 32, category: 9, emoji: '👖' },
  { type: 17, slot: 4, name: 'Adamantine Pants', level: 70, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 26, category: 9, emoji: '👖' },
  { type: 18, slot: 4, name: 'Ancient Pants', level: 72, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 28, category: 9, emoji: '👖' },
  { type: 19, slot: 4, name: 'Storm Crow Pants', level: 74, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 34, category: 9, emoji: '👖' },
  { type: 20, slot: 4, name: 'Black Dragon Pants', level: 84, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 40, category: 9, emoji: '👖' },
  { type: 21, slot: 4, name: 'Grand Soul Pants', level: 86, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 30, category: 9, emoji: '👖' },
  { type: 22, slot: 4, name: 'Demonic Pants', level: 86, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 37, category: 9, emoji: '👖' },
  { type: 23, slot: 4, name: 'Divine Pants', level: 88, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 39, category: 9, emoji: '👖' },
  { type: 24, slot: 4, name: 'Dark Steel Pants', level: 92, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 31, category: 9, emoji: '👖' },
  { type: 25, slot: 4, name: 'Dark Phoenix Pants', level: 96, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 54, category: 9, emoji: '👖' },
  { type: 26, slot: 4, name: 'Thunder Hawk Pants', level: 99, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 49, category: 9, emoji: '👖' },
  { type: 27, slot: 4, name: 'Red Spirit Pants', level: 100, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 48, category: 9, emoji: '👖' },
  { type: 28, slot: 4, name: 'Valiant Pants', level: 101, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 41, category: 9, emoji: '👖' },
  { type: 29, slot: 4, name: 'Glorious Pants', level: 101, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 35, category: 9, emoji: '👖' },
  { type: 30, slot: 4, name: 'Dark Master Pants', level: 110, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 39, category: 9, emoji: '👖' },
  { type: 31, slot: 4, name: 'Great Dragon Pants', level: 113, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 65, category: 9, emoji: '👖' },
  { type: 32, slot: 4, name: 'Dark Soul Pants', level: 117, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 39, category: 9, emoji: '👖' },
  { type: 33, slot: 4, name: 'Hurricane Pants', level: 122, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 61, category: 9, emoji: '👖' },
  { type: 34, slot: 4, name: 'Dragon Knight Pants', level: 134, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 78, category: 9, emoji: '👖' },
  { type: 35, slot: 4, name: 'Venom Mist Pants', level: 135, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 55, category: 9, emoji: '👖' },
  { type: 36, slot: 4, name: 'Sylphid Ray Pants', level: 135, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 61, category: 9, emoji: '👖' },
  { type: 37, slot: 4, name: 'Volcano Pants', level: 135, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 74, category: 9, emoji: '👖' },
  { type: 38, slot: 4, name: 'Sunlight Pants', level: 140, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 52, category: 9, emoji: '👖' },

  // Category 10 - Gloves
  { type: 0, slot: 5, name: 'Leather Gloves', level: 4, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 2, category: 10, emoji: '🧤' },
  { type: 1, slot: 5, name: 'Vine Gloves', level: 4, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 2, category: 10, emoji: '🧤' },
  { type: 2, slot: 5, name: 'Silk Gloves', level: 14, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 4, category: 10, emoji: '🧤' },
  { type: 3, slot: 5, name: 'Bone Gloves', level: 14, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 5, category: 10, emoji: '🧤' },
  { type: 4, slot: 5, name: 'Scale Gloves', level: 22, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 7, category: 10, emoji: '🧤' },
  { type: 5, slot: 5, name: 'Violent Wind Gloves', level: 24, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 9, category: 10, emoji: '🧤' },
  { type: 6, slot: 5, name: 'Wind Gloves', level: 26, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 6, category: 10, emoji: '🧤' },
  { type: 7, slot: 5, name: 'Sphinx Gloves', level: 28, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 8, category: 10, emoji: '🧤' },
  { type: 8, slot: 5, name: 'Brass Gloves', level: 32, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 9, category: 10, emoji: '🧤' },
  { type: 9, slot: 5, name: 'Spirit Gloves', level: 38, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 9, category: 10, emoji: '🧤' },
  { type: 10, slot: 5, name: 'Plate Gloves', level: 42, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 12, category: 10, emoji: '🧤' },
  { type: 11, slot: 5, name: 'Light Plate Gloves', level: 42, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 12, category: 10, emoji: '🧤' },
  { type: 12, slot: 5, name: 'Red Wing Gloves', level: 44, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 13, category: 10, emoji: '🧤' },
  { type: 13, slot: 5, name: 'Guardian Gloves', level: 50, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 15, category: 10, emoji: '🧤' },
  { type: 14, slot: 5, name: 'Adamantine Gloves', level: 57, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 18, category: 10, emoji: '🧤' },
  { type: 15, slot: 5, name: 'Ashcrow Gloves', level: 61, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 18, category: 10, emoji: '🧤' },
  { type: 16, slot: 5, name: 'Eclipse Gloves', level: 61, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 15, category: 10, emoji: '🧤' },
  { type: 17, slot: 5, name: 'Iris Gloves', level: 61, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 22, category: 10, emoji: '🧤' },
  { type: 18, slot: 5, name: 'Ancient Gloves', level: 61, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 19, category: 10, emoji: '🧤' },
  { type: 19, slot: 5, name: 'Storm Crow Gloves', level: 70, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 20, category: 10, emoji: '🧤' },
  { type: 20, slot: 5, name: 'Grand Soul Gloves', level: 70, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 20, category: 10, emoji: '🧤' },
  { type: 21, slot: 5, name: 'Demonic Gloves', level: 70, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 26, category: 10, emoji: '🧤' },
  { type: 22, slot: 5, name: 'Divine Gloves', level: 72, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 29, category: 10, emoji: '🧤' },
  { type: 23, slot: 5, name: 'Dark Steel Gloves', level: 75, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 21, category: 10, emoji: '🧤' },
  { type: 24, slot: 5, name: 'Black Dragon Gloves', level: 76, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 22, category: 10, emoji: '🧤' },
  { type: 25, slot: 5, name: 'Red Spirit Gloves', level: 84, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 38, category: 10, emoji: '🧤' },
  { type: 26, slot: 5, name: 'Dark Phoenix Gloves', level: 86, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 37, category: 10, emoji: '🧤' },
  { type: 27, slot: 5, name: 'Dark Soul Gloves', level: 87, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 30, category: 10, emoji: '🧤' },
  { type: 28, slot: 5, name: 'Thunder Hawk Gloves', level: 88, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 34, category: 10, emoji: '🧤' },
  { type: 29, slot: 5, name: 'Dark Master Gloves', level: 89, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 29, category: 10, emoji: '🧤' },
  { type: 30, slot: 5, name: 'Valiant Gloves', level: 91, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 27, category: 10, emoji: '🧤' },
  { type: 31, slot: 5, name: 'Glorious Gloves', level: 91, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 25, category: 10, emoji: '🧤' },
  { type: 32, slot: 5, name: 'Great Dragon Gloves', level: 94, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 48, category: 10, emoji: '🧤' },
  { type: 33, slot: 5, name: 'Hurricane Gloves', level: 102, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 45, category: 10, emoji: '🧤' },
  { type: 34, slot: 5, name: 'Sunlight Gloves', level: 110, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 40, category: 10, emoji: '🧤' },
  { type: 35, slot: 5, name: 'Venom Mist Gloves', level: 111, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 44, category: 10, emoji: '🧤' },
  { type: 36, slot: 5, name: 'Sylphid Ray Gloves', level: 111, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 50, category: 10, emoji: '🧤' },
  { type: 37, slot: 5, name: 'Dragon Knight Gloves', level: 114, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 60, category: 10, emoji: '🧤' },
  { type: 38, slot: 5, name: 'Volcano Gloves', level: 127, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 55, category: 10, emoji: '🧤' },

  // Category 11 - Boots
  { type: 0, slot: 6, name: 'Leather Boots', level: 5, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 2, category: 11, emoji: '🥾' },
  { type: 1, slot: 6, name: 'Vine Boots', level: 5, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 2, category: 11, emoji: '🥾' },
  { type: 2, slot: 6, name: 'Silk Boots', level: 15, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 4, category: 11, emoji: '🥾' },
  { type: 3, slot: 6, name: 'Bone Boots', level: 16, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 6, category: 11, emoji: '🥾' },
  { type: 4, slot: 6, name: 'Scale Boots', level: 22, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 8, category: 11, emoji: '🥾' },
  { type: 5, slot: 6, name: 'Violent Wind Boots', level: 26, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 11, category: 11, emoji: '🥾' },
  { type: 6, slot: 6, name: 'Wind Boots', level: 27, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 7, category: 11, emoji: '🥾' },
  { type: 7, slot: 6, name: 'Sphinx Boots', level: 30, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 9, category: 11, emoji: '🥾' },
  { type: 8, slot: 6, name: 'Brass Boots', level: 32, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 10, category: 11, emoji: '🥾' },
  { type: 9, slot: 6, name: 'Spirit Boots', level: 40, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 10, category: 11, emoji: '🥾' },
  { type: 10, slot: 6, name: 'Plate Boots', level: 42, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 12, category: 11, emoji: '🥾' },
  { type: 11, slot: 6, name: 'Light Plate Boots', level: 45, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 13, category: 11, emoji: '🥾' },
  { type: 12, slot: 6, name: 'Red Wing Boots', level: 46, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 15, category: 11, emoji: '🥾' },
  { type: 13, slot: 6, name: 'Guardian Boots', level: 52, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 16, category: 11, emoji: '🥾' },
  { type: 14, slot: 6, name: 'Adamantine Boots', level: 60, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 20, category: 11, emoji: '🥾' },
  { type: 15, slot: 6, name: 'Ancient Boots', level: 65, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 21, category: 11, emoji: '🥾' },
  { type: 16, slot: 6, name: 'Ashcrow Boots', level: 68, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 19, category: 11, emoji: '🥾' },
  { type: 17, slot: 6, name: 'Eclipse Boots', level: 68, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 17, category: 11, emoji: '🥾' },
  { type: 18, slot: 6, name: 'Iris Boots', level: 68, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 23, category: 11, emoji: '🥾' },
  { type: 19, slot: 6, name: 'Storm Crow Boots', level: 72, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 22, category: 11, emoji: '🥾' },
  { type: 20, slot: 6, name: 'Grand Soul Boots', level: 76, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 22, category: 11, emoji: '🥾' },
  { type: 21, slot: 6, name: 'Demonic Boots', level: 76, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 28, category: 11, emoji: '🥾' },
  { type: 22, slot: 6, name: 'Black Dragon Boots', level: 78, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 24, category: 11, emoji: '🥾' },
  { type: 23, slot: 6, name: 'Divine Boots', level: 81, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 30, category: 11, emoji: '🥾' },
  { type: 24, slot: 6, name: 'Dark Steel Boots', level: 83, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 25, category: 11, emoji: '🥾' },
  { type: 25, slot: 6, name: 'Red Spirit Boots', level: 87, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 40, category: 11, emoji: '🥾' },
  { type: 26, slot: 6, name: 'Thunder Hawk Boots', level: 92, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 37, category: 11, emoji: '🥾' },
  { type: 27, slot: 6, name: 'Dark Phoenix Boots', level: 93, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 40, category: 11, emoji: '🥾' },
  { type: 28, slot: 6, name: 'Dark Master Boots', level: 95, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 33, category: 11, emoji: '🥾' },
  { type: 29, slot: 6, name: 'Dark Soul Boots', level: 95, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 31, category: 11, emoji: '🥾' },
  { type: 30, slot: 6, name: 'Great Dragon Boots', level: 98, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 50, category: 11, emoji: '🥾' },
  { type: 31, slot: 6, name: 'Valiant Boots', level: 98, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 29, category: 11, emoji: '🥾' },
  { type: 32, slot: 6, name: 'Glorious Boots', level: 98, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 29, category: 11, emoji: '🥾' },
  { type: 33, slot: 6, name: 'Hurricane Boots', level: 110, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 50, category: 11, emoji: '🥾' },
  { type: 34, slot: 6, name: 'Dragon Knight Boots', level: 119, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 63, category: 11, emoji: '🥾' },
  { type: 35, slot: 6, name: 'Venom Mist Boots', level: 119, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 47, category: 11, emoji: '🥾' },
  { type: 36, slot: 6, name: 'Sylphid Ray Boots', level: 119, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 53, category: 11, emoji: '🥾' },
  { type: 37, slot: 6, name: 'Sunlight Boots', level: 121, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 44, category: 11, emoji: '🥾' },
  { type: 38, slot: 6, name: 'Volcano Boots', level: 131, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 61, category: 11, emoji: '🥾' },

  // Category 12 - Rings (min level 41, no damage/defense, only options)
  { type: 0, slot: 7, name: 'Ring of Ice', level: 41, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 12, emoji: '💍' },
  { type: 1, slot: 7, name: 'Ring of Poison', level: 50, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 12, emoji: '💍' },
  { type: 2, slot: 7, name: 'Ring of Fire', level: 60, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 12, emoji: '💍' },
  { type: 3, slot: 7, name: 'Ring of Earth', level: 70, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 12, emoji: '💍' },
  { type: 4, slot: 7, name: 'Ring of Wind', level: 80, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 12, emoji: '💍' },
  { type: 5, slot: 7, name: 'Ring of Magic', level: 100, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 12, emoji: '💍' },

  // Category 13 - Pendants (min level 41, no damage/defense, only options)
  { type: 0, slot: 8, name: 'Pendant of Lightning', level: 41, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 13, emoji: '📿' },
  { type: 1, slot: 8, name: 'Pendant of Fire', level: 50, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 13, emoji: '📿' },
  { type: 2, slot: 8, name: 'Pendant of Ice', level: 60, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 13, emoji: '📿' },
  { type: 3, slot: 8, name: 'Pendant of Wind', level: 70, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 13, emoji: '📿' },
  { type: 4, slot: 8, name: 'Pendant of Water', level: 80, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 13, emoji: '📿' },
  { type: 5, slot: 8, name: 'Pendant of Ability', level: 100, damageMin: 0, damageMax: 0, attackSpeed: 0, defenseValue: 0, category: 13, emoji: '📿' },
];

export async function GET() {
  try {
    let created = 0;
    let skipped = 0;

    // Seed items - upsert to add new items without duplicating existing ones
    for (const item of items) {
      const existing = await prisma.item.findFirst({
        where: { name: item.name, category: item.category }
      });

      if (!existing) {
        await prisma.item.create({ data: item });
        created++;
      } else {
        skipped++;
      }
    }

    return NextResponse.json({
      success: true,
      message: `Seeding complete: ${created} new items added, ${skipped} already existed`
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json({
      success: false,
      error: String(error)
    }, { status: 500 });
  }
}
